# 1. DataLoader
batch_size: 512
num_workers: 8

task_config:
  sample_input_size: 10 97 768 # Batch length dimmension


# 3. Optimizer
optimizer: adam
optimizer_config:
  lr: 0.001
  weight_decay: 0


# 4. LossFunction
loss: clip_ce


# 5. Scheduler
scheduler: none
scheduler_config:
  step_size: 50
  gamma: 0.9
  last_epoch: -1


# 6. Trainer
max_epoch: 200
devices: -1
accelerator: cuda
num_sanity_val_steps: 2


# 7. Checkpoint
resume_checkpoint: null
checkpoint_config:
  save_top_k: 5
  monitor: "val_ACC"
  mode: "max"
  filename: "emotion-recognition-{epoch:02d}-{val_loss:.2f}-{val_ACC:02.2f}"


# 8. Random Seed
random_seed: 2301235

# 2. Model
model: EmotionRecognitionModule
model_config:
  input_dim: 768