# 1. DataLoader
training_dataset_config:
  data_name: 'fluent'
  root: '/home/nas4/DB/fluent_speech_commands/fluent_speech_commands_dataset_feat_1_12'
  vq_root: '/home/nas4/DB/fluent_speech_commands/fluent_speech_commands_dataset_feat_vq'
  subset: 'training'
  ext: 'pt'
train_loader_config:
  shuffle: True
validation_dataset_config:
  data_name: 'fluent'
  root: '/home/nas4/DB/fluent_speech_commands/fluent_speech_commands_dataset_feat_1_12'
  vq_root: '/home/nas4/DB/fluent_speech_commands/fluent_speech_commands_dataset_feat_vq'
  subset: 'validation'
  ext: 'pt'
validation_loader_config:
  shuffle: False
test_dataset_config:
  data_name: 'fluent'
  root: '/home/nas4/DB/fluent_speech_commands/fluent_speech_commands_dataset_feat_1_12'
  vq_root: '/home/nas4/DB/fluent_speech_commands/fluent_speech_commands_dataset_feat_vq'
  subset: 'testing'
  ext: 'pt'
test_loader_config:
  shuffle: False

batch_size: 512
num_workers: 8

task_config:
  metric: 'acc'
  sample_input_size: 10 40 768


# 2. Optimizer
optimizer: adam
optimizer_config:
  lr: 0.001
  weight_decay: 0


# 3. LossFunction
loss: clip_ce


# 4. Scheduler
scheduler: none
scheduler_config:
  step_size: 50
  gamma: 0.9
  last_epoch: -1


# 5. Trainer
max_epoch: 200
devices: -1
accelerator: cuda
num_sanity_val_steps: 2
profiler: null # advanced


# 6. Checkpoint
resume_checkpoint: null
checkpoint_config:
  save_top_k: 5
  monitor: "val_ACC"
  mode: "max"
  filename: "AVG-SpeechCommandsV2-{epoch:02d}-{val_loss:.2f}-{val_ACC:02.2f}"


# 7. Random Seed
random_seed: 2301235

model: IntentClassificationModule
model_config:
  input_dim: 768
  num_classes: 31