batch_size: 4096
num_workers: 8

task_config:
  metric: 'acc'
  sample_input_size: 10 40 768


# 2. Optimizer
optimizer: adam
optimizer_config:
  lr: 0.01
  weight_decay: 0


# 3. LossFunction
loss: clip_ce


# 4. Scheduler
scheduler: none
scheduler_config:
  step_size: 50
  gamma: 0.9
  last_epoch: -1


# 5. Trainer
max_epoch: 200
devices: -1
accelerator: cuda
num_sanity_val_steps: 2
profiler: null # advanced


# 6. Checkpoint
resume_checkpoint: null
checkpoint_config:
  save_top_k: 5
  monitor: "val_ACC"
  mode: "max"
  filename: "AVG-SpeechCommandsV2-{epoch:02d}-{val_loss:.2f}-{val_ACC:02.2f}"


# 7. Random Seed
random_seed: 2301235

model: KeywordSpottingModule
model_config:
  input_dim: *feature_dim
  num_classes: 35