# 1. DataLoader
training_dataset_config:
  data_name: 'voxceleb'
<<<<<<< HEAD
  root: 'data/voxceleb1_1_12'
  subset: 'training'
  url: 'vrfy_split_debug.txt'
=======
  root: '/home/nas3/user/jeonko/spc_embedding/data/voxceleb1_1_12'
  subset: 'training'
  url: 'vrfy_split.txt'
>>>>>>> 7526fbe449593d87e0d22f84cd10763e1de28e44
  ext: 'pt'
train_loader_config:
  shuffle: True
test_dataset_config:
  data_name: 'voxceleb'
<<<<<<< HEAD
  root: 'data/voxceleb1_1_12'
=======
  root: '/home/nas3/user/jeonko/spc_embedding/data/voxceleb1_1_12'
>>>>>>> 7526fbe449593d87e0d22f84cd10763e1de28e44
  subset: 'validation'
  url: 'valid_metadata.txt'
  ext: 'pt'
test_loader_config:
  shuffle: False

batch_size: 32
num_workers: 8


# 2. Model
model: SpeakerVerificationModule
model_config:
  input_dim: 768
  num_classes: 1211 # 1251
  head_type: 'avgpool'
  layer_ids: -1 # Utilize the Last layer
  whitening: false
<<<<<<< HEAD
=======
  embedding_size: 512
>>>>>>> 7526fbe449593d87e0d22f84cd10763e1de28e44

task_config:
  metric: 'eer'
  sample_input_size: 10 40 768


# 3. Optimizer
optimizer: adam
optimizer_config:
  lr: 0.001
  weight_decay: 0.0001


# 4. LossFunction
loss: amsoftmax


# 5. Scheduler
scheduler: steplr
scheduler_config:
  step_size: 50
  gamma: 0.9
  last_epoch: -1


# 6. Trainer
default_root_dir: ./results/asv_avg_layer_12
profiler: null #advanced
max_epoch: 200
devices: -1
accelerator: cuda
num_sanity_val_steps: 2


# 7. Checkpoint
<<<<<<< HEAD
resume_checkpoint: "results/asv_avg_layer_12/lightning_logs/version_0/checkpoints/AVG-SpeechCommandsV2-epoch=18-val_loss=9.20-val_ACC=72.37.ckpt" #"
=======
resume_checkpoint: null #"results/asv_avg_layer_12/lightning_logs/version_0/checkpoints/AVG-SpeechCommandsV2-epoch=27-val_loss=9.09-val_ACC=72.04.ckpt" #"
>>>>>>> 7526fbe449593d87e0d22f84cd10763e1de28e44
checkpoint_config:
  save_top_k: 5
  monitor: "val_EER"
  mode: "min"
<<<<<<< HEAD
  filename: "AVG-SpeechCommandsV2-{epoch:02d}-{val_loss:.2f}-{val_EER:02.2f}"
=======
  filename: "SV-{epoch:02d}-{val_loss:.2f}-{val_EER:02.2f}"
>>>>>>> 7526fbe449593d87e0d22f84cd10763e1de28e44


# 8. Random Seed
random_seed: 2301235