# 1. DataLoader
training_dataset_config:
  data_name: 'iemocap'
  root: '/home/nas4/DB/IEMOCAP'
  sessions: [1, 2, 3, 4]
  utterance_type: null # "scripted" or "improvised" or null. if null it contain both ["scripted" and "improvised"]
  ext: 'pt'
  feature_path_tag: '_feat_1_12'
  vq_path_tag: '_feat_vq'
  final_classes: ["neu", "hap", "ang", "sad" , "exc"] # we drop the unbalance emotion classes to leave the final four classes (neutral, happy, sad, angry)
train_loader_config:
  shuffle: True
test_dataset_config:
  data_name: 'iemocap'
  root: '/home/nas4/DB/IEMOCAP'
  sessions: [5]
  utterance_type: null
  ext: 'pt'
  feature_path_tag: '_feat_1_12'
  vq_path_tag: '_feat_vq'
  final_classes: ["neu", "hap", "ang", "sad", "exc"] # we drop the unbalance emotion classes to leave the final four classes (neutral, happy, sad, angry)
test_loader_config:
  shuffle: False