# 1. DataLoader
dataloader: dataloader_esc_50
batch_size: 32
num_workers: 8
training_dataset_config:
  dataset: ./data/ESC-50-master/meta/esc50.csv
  fold: 1
  audio_path: ./data/ESC-50-master/audio
  eval_mode: False
test_dataset_config:
  dataset: ./data/ESC-50-master/meta/esc50.csv
  fold: 1
  audio_path: ./data/ESC-50-master/audio
  eval_mode: True


# 2. Model
model: wac2vec_feature_extractor_v2
model_config:
  num_classes: 50


# 2. Optimizer
optimizer: adam
optimizer_config:
  lr: 0.001
  weight_decay: 0

# 2. LossFunction
loss: clip_ce

# 2. Scheduler
scheduler: steplr
scheduler_config:
  step_size: 30
  gamma: 0.95


# trainer
default_root_dir: ./results/esc_50_fold_1_v2
profiler: advanced
max_epoch: 200
devices: 1
accelerator: gpu
num_sanity_val_steps: -1


# save, load
resume_checkpoint: 

# random seed
random_seed: 2301235